# Generated by Django 4.1.7 on 2023-08-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='sub_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='sub_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
