# Generated by Django 4.1.7 on 2023-08-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_accountprofile_sub_expire_accountprofile_sub_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripepayment",
            old_name="user",
            new_name="profile",
        ),
    ]
