# Generated by Django 4.1.7 on 2023-08-12 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_accountpayment_stripepayment_accountprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
