# Generated by Django 4.1.7 on 2023-08-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_stripepayment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="stripepayment",
            name="user",
        ),
    ]
