# Generated by Django 4.1.7 on 2023-08-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_stripepayment_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripepayment",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.accountprofile",
            ),
            preserve_default=False,
        ),
    ]
