# Generated by Django 4.1.7 on 2023-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_remove_stripepayment_profile_stripepayment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="sub_expire",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="sub_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
