# Generated by Django 4.1.7 on 2023-08-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_accountprofile_sub_expire_and_more'),
        ('account', '0009_rename_user_stripepayment_profile'),
    ]

    operations = [
    ]
