# Generated by Django 4.1.7 on 2023-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_profile_stripepayment_user_account_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=60, unique=True, verbose_name='username'),
        ),
    ]
