# Generated by Django 4.1.7 on 2023-08-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_is_superuser_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=60, verbose_name='username'),
        ),
    ]
