# Generated by Django 4.1.7 on 2023-08-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
