# Generated by Django 4.1.7 on 2023-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('AT', 'Active'), ('IA', 'Inactive'), ('TL', 'Trial'), ('BT', 'Beta Tester')], default='IA', max_length=2),
        ),
    ]
