# Generated by Django 4.1.7 on 2023-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_cus_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_sub_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
