# Generated by Django 4.1.7 on 2023-08-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_stripe_cus_id_account_stripe_sub_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountProfile',
        ),
    ]
