# Generated by Django 4.1.7 on 2023-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_stripepayment_user_delete_accountprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="sub_auto_renew",
            field=models.BooleanField(default=True),
        ),
    ]
