# Generated by Django 4.1.7 on 2023-08-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_account_sub_auto_renew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cancel_at_end',
        ),
    ]
