# Generated by Django 4.1.7 on 2023-04-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MensRegSize',
            new_name='MensJeanBigTallSize',
        ),
        migrations.RenameModel(
            old_name='MenJeansRegSize',
            new_name='MensJeanSize',
        ),
        migrations.AddField(
            model_name='allowedsize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_id', to='size.sizelist'),
        ),
        migrations.AlterUniqueTogether(
            name='allowedsize',
            unique_together={('category', 'size')},
        ),
        migrations.RemoveField(
            model_name='allowedsize',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='allowedsize',
            name='object_id',
        ),
    ]
