# Generated by Django 4.1.7 on 2023-04-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0002_menssize_sizelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedsize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_name', to='size.sizelist'),
        ),
    ]
