# Generated by Django 4.1.7 on 2023-03-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0002_alter_searchprofile_brand'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
