# Generated by Django 4.1.7 on 2023-03-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_condition_brand_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='keyword',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
