# Generated by Django 4.1.7 on 2023-04-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_bigtallsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='specslist',
            name='list_order',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
