# Generated by Django 4.1.7 on 2023-03-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_brand_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sleevelength',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
