# Generated by Django 4.1.7 on 2023-04-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_specslist_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specslist',
            options={'ordering': ['list_order']},
        ),
    ]
