# Generated by Django 4.1.7 on 2023-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_alter_brand_name_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
