# Generated by Django 4.1.7 on 2023-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0005_alter_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
