# Generated by Django 4.1.7 on 2023-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0007_alter_specslist_options_remove_specslist_list_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensPantsInseam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='MenJeansWaistSize',
            new_name='MensWaistSize',
        ),
    ]
