# Generated by Django 4.1.7 on 2023-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0002_alter_searchprofile_unique_together_and_more'),
        ('specs', '0007_alter_brand_code_alter_brand_keyword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
