# Generated by Django 4.1.7 on 2023-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0008_menspantsinseam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSizeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='menspantsinseam',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menswaistsize',
            options={'ordering': ['name']},
        ),
    ]
