# Generated by Django 4.1.7 on 2023-05-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsizes',
            name='size_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizetype', to='specs.genericsizetype'),
        ),
    ]
