# Generated by Django 4.1.7 on 2023-03-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
