# Generated by Django 4.1.7 on 2023-05-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0012_alter_genericsizes_size_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericSizes',
            new_name='GenericSize',
        ),
    ]
