# Generated by Django 4.1.7 on 2023-06-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0016_menspantbtsize_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menspantsize',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='menspantsize',
            unique_together={('name', 'size_type')},
        ),
        migrations.DeleteModel(
            name='MensPantBTSize',
        ),
    ]
