# Generated by Django 4.1.7 on 2023-06-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0017_alter_menspantsize_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensPantSize',
        ),
    ]
