# Generated by Django 4.1.7 on 2023-06-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0018_delete_menspantsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensPantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.genericsizetype')),
            ],
            options={
                'unique_together': {('name', 'size_type')},
            },
        ),
    ]
