# Generated by Django 4.1.7 on 2023-06-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0019_menspantsize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensPantInseam',
            new_name='MensPantInseamSize',
        ),
    ]
