# Generated by Django 4.1.7 on 2023-06-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0024_menstopfabric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensTopFabric',
            new_name='MensGenericFabric',
        ),
    ]
