# Generated by Django 4.1.7 on 2023-07-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0027_menspantclosuresize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensPantClosureSize',
            new_name='MensPantClosure',
        ),
    ]
