# Generated by Django 4.1.7 on 2023-07-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0031_genericfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfeature',
            name='size_type',
        ),
    ]
