# Generated by Django 4.1.7 on 2023-10-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0034_mensshortinseamsize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeType',
            new_name='WomensSizeType',
        ),
    ]
