# Generated by Django 4.1.7 on 2023-10-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0036_womenssizetop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WomensSizeTop',
            new_name='WomensTopSize',
        ),
    ]
