# Generated by Django 4.1.7 on 2023-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0038_alter_womenstopsize_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenstopsize',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='womenstopsize',
            unique_together={('name', 'size_type')},
        ),
    ]
