# Generated by Django 4.1.7 on 2023-03-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0010_specslist'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.specslist')),
            ],
            options={
                'unique_together': {('category', 'spec')},
            },
        ),
    ]
