# Generated by Django 4.1.7 on 2023-05-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='display_name',
            new_name='display',
        ),
    ]
