# Generated by Django 4.1.7 on 2023-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_allowedspecs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ebay_cat_id',
            new_name='code',
        ),
    ]
