# Generated by Django 4.1.7 on 2023-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_display_name_category_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
