# Generated by Django 4.1.7 on 2023-03-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_size'),
        ('category', '0003_rename_ebay_cat_id_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedspecs',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_specs', to='specs.specslist'),
        ),
    ]
