# Generated by Django 4.1.7 on 2023-03-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0012_alter_brand_options'),
        ('category', '0004_alter_allowedspecs_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedspecs',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_names', to='specs.specslist'),
        ),
    ]
