# Generated by Django 4.1.7 on 2023-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_allowedspecs_spec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedSpecs',
        ),
    ]
