# Generated by Django 4.1.7 on 2023-05-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0009_genericsizetype_alter_menspantsinseam_options_and_more'),
        ('category', '0005_rename_display_category_qualifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericMensTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.color')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.condition')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.material')),
                ('patterns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.sleevelength')),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.genericsizetype')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='itemType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.itemtype'),
        ),
    ]
