# Generated by Django 4.1.7 on 2023-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_itemtype_genericmenstop_category_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='identifier',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
