# Generated by Django 4.1.7 on 2023-05-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_rename_itemtype_category_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericmenstop',
            old_name='patterns',
            new_name='pattern',
        ),
    ]
