# Generated by Django 4.1.7 on 2023-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_rename_patterns_genericmenstop_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenstop',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
