# Generated by Django 4.1.7 on 2023-05-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_pattern'),
        ('category', '0010_genericmenstop_keywords_genericmenstop_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericmenstop',
            old_name='model',
            new_name='item_model',
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='sleeve_length',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='specs.sleevelength'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specs.color'),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='condition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specs.condition'),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specs.material'),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='pattern',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specs.pattern'),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='size_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specs.genericsizetype'),
        ),
    ]
