# Generated by Django 4.1.7 on 2023-05-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_rename_model_genericmenstop_item_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericMensTop',
        ),
    ]
