# Generated by Django 4.1.7 on 2023-10-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0025_genericwomenstop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensJacket',
            new_name='GenericMensJacket',
        ),
    ]
