# Generated by Django 4.1.7 on 2023-10-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0025_genericwomenstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensJacket',
            fields=[
                ('menstop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.menstop')),
                ('closure', models.CharField(blank=True, max_length=30, null=True)),
                ('style', models.CharField(blank=True, max_length=30, null=True)),
                ('jacket_type', models.CharField(blank=True, max_length=30, null=True)),
                ('shell', models.CharField(blank=True, max_length=30, null=True)),
                ('lining', models.CharField(blank=True, max_length=30, null=True)),
                ('insulation', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.menstop',),
        ),
        migrations.RenameModel(
            old_name='GenericMensPant',
            new_name='MensPant',
        ),
        migrations.RenameModel(
            old_name='GenericMensShort',
            new_name='MensShort',
        ),
        migrations.RenameModel(
            old_name='GenericWomensTop',
            new_name='WomensTop',
        ),
        migrations.RenameField(
            model_name='genericmenspolo',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameField(
            model_name='mensactivewearpant',
            old_name='genericmenspant_ptr',
            new_name='menspant_ptr',
        ),
        migrations.RenameField(
            model_name='mensactiveweartop',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameField(
            model_name='mensdressshirt',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameField(
            model_name='menshoodiessweatshirts',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameField(
            model_name='mensshort',
            old_name='genericmenspant_ptr',
            new_name='menspant_ptr',
        ),
        migrations.RenameField(
            model_name='menssweater',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameField(
            model_name='menstshirt',
            old_name='genericmenstop_ptr',
            new_name='menstop_ptr',
        ),
        migrations.RenameModel(
            old_name='GenericMensTop',
            new_name='MensTop',
        ),
        migrations.DeleteModel(
            name='GenericMensJacket',
        ),
    ]
