# Generated by Django 4.1.7 on 2023-03-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'ordering': ['brand__name'],
                'unique_together': {('brand', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forsale', models.PositiveIntegerField()),
                ('avg_forsale_price', models.FloatField()),
                ('sold', models.PositiveIntegerField()),
                ('avg_sold_price', models.FloatField()),
                ('ratio', models.FloatField()),
                ('search_url', models.URLField(max_length=300)),
                ('keywords', models.TextField(null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='searchprofile.searchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_line', to='searchprofile.searchresult')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_id', to='specs.specslist')),
            ],
            options={
                'unique_together': {('category', 'spec')},
            },
        ),
    ]
