# Generated by Django 4.1.7 on 2023-03-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandprofile', '0001_initial'),
        ('searchprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprofile',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brandprofile.brand'),
        ),
    ]
