# Generated by Django 4.1.7 on 2023-06-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0012_delete_genericmenstop'),
        ('searchprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchprofile',
            options={'ordering': ['brand__name']},
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searchprofile.brand'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='searchprofile',
            unique_together={('brand', 'category', 'user')},
        ),
    ]
