# Generated by Django 4.1.7 on 2023-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='searchprofile',
            name='brand',
        ),
    ]
