# Generated by Django 4.1.7 on 2023-03-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0009_brand'),
        ('searchprofile', '0002_alter_searchprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specs.brand'),
            preserve_default=False,
        ),
    ]
