# Generated by Django 4.1.7 on 2023-06-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0002_alter_searchprofile_options_searchprofile_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='heading',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
