# Generated by Django 4.1.7 on 2023-03-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0010_specslist'),
        ('category', '0002_allowedspecs'),
        ('searchprofile', '0003_searchprofile_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchprofile',
            unique_together={('brand', 'category')},
        ),
        migrations.RemoveField(
            model_name='searchprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='searchprofile',
            name='object_id',
        ),
    ]
