# Generated by Django 4.1.7 on 2023-06-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0003_searchresult_heading_searchresult_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericmenstop',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='genericmenstop',
            name='keywords',
        ),
    ]
