# Generated by Django 4.1.7 on 2023-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0004_remove_genericmenstop_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmenstop',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='pattern',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='size_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenstop',
            name='sleeve_length',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
