# Generated by Django 4.1.7 on 2023-03-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0004_alter_searchprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forsale', models.PositiveIntegerField()),
                ('avg_forsale_price', models.FloatField()),
                ('sold', models.PositiveIntegerField()),
                ('avg_sold_price', models.FloatField()),
                ('ratio', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchprofile.searchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100)),
                ('condition_value', models.CharField(max_length=100)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchprofile.searchresult')),
            ],
        ),
    ]
