# Generated by Django 4.1.7 on 2023-06-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0006_alter_genericmenstop_result_genericmenspants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericMensPants',
            new_name='GenericMensPant',
        ),
    ]
