# Generated by Django 4.1.7 on 2023-03-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0007_searchresult_last_upadated_alter_resultspecs_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='last_upadated',
        ),
    ]
