# Generated by Django 4.1.7 on 2023-06-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0007_rename_genericmenspants_genericmenspant'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenspant',
            name='vintage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='vintage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
