# Generated by Django 4.1.7 on 2023-03-21 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0008_remove_searchresult_last_upadated'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
