# Generated by Django 4.1.7 on 2023-06-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0008_genericmenspant_vintage_genericmenstop_vintage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenspant',
            name='fit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='fit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
