# Generated by Django 4.1.7 on 2023-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0009_genericmenspant_fit_genericmenstop_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenstop',
            name='collar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
