# Generated by Django 4.1.7 on 2023-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0010_alter_searchresult_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
