# Generated by Django 4.1.7 on 2023-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0010_genericmenstop_collar'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenspant',
            name='rise',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
