# Generated by Django 4.1.7 on 2023-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0011_genericmenspant_rise'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmenspant',
            name='fabric',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genericmenstop',
            name='fabric',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
