# Generated by Django 4.1.7 on 2023-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0012_alter_searchresult_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='search_url',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
