# Generated by Django 4.1.7 on 2023-06-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0012_genericmenspant_fabric_genericmenstop_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMensPolo',
            fields=[
                ('genericmenstop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.genericmenstop')),
                ('neckline', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.genericmenstop',),
        ),
    ]
