# Generated by Django 4.1.7 on 2023-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0013_genericmenspolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='search_url',
            field=models.URLField(max_length=350),
        ),
    ]
