# Generated by Django 4.1.7 on 2023-03-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0014_rename_condition_name_resultspecs_spec_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspecs',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
    ]
