# Generated by Django 4.1.7 on 2023-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0014_alter_searchresult_search_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='heading',
            field=models.CharField(max_length=200),
        ),
    ]
