# Generated by Django 4.1.7 on 2023-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0015_resultspecs_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultspecs',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
