# Generated by Django 4.1.7 on 2023-07-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0016_genericmenspant_closure'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMensShort',
            fields=[
                ('genericmenspant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.genericmenspant')),
                ('style', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.genericmenspant',),
        ),
    ]
