# Generated by Django 4.1.7 on 2023-03-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0016_alter_resultspecs_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultspecs',
            name='keywords',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
