# Generated by Django 4.1.7 on 2023-03-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0017_remove_resultspecs_keywords_searchresult_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchprofile',
            options={'ordering': ['brand__name']},
        ),
    ]
