# Generated by Django 4.1.7 on 2023-07-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0017_genericmensshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMensJacket',
            fields=[
                ('genericmenstop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.genericmenstop')),
                ('closure', models.CharField(blank=True, max_length=30, null=True)),
                ('style', models.CharField(blank=True, max_length=30, null=True)),
                ('jacket_type', models.CharField(blank=True, max_length=30, null=True)),
                ('shell', models.CharField(blank=True, max_length=30, null=True)),
                ('lining', models.CharField(blank=True, max_length=30, null=True)),
                ('insulation', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.genericmenstop',),
        ),
        migrations.AlterField(
            model_name='genericmenspant',
            name='closure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenspant',
            name='inseam',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenspant',
            name='rise',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmenspant',
            name='waist_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genericmensshort',
            name='style',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
