# Generated by Django 4.1.7 on 2023-03-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0012_alter_brand_options'),
        ('category', '0006_delete_allowedspecs'),
        ('searchprofile', '0018_alter_searchprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_names', to='specs.specslist')),
            ],
            options={
                'unique_together': {('category', 'spec')},
            },
        ),
    ]
