# Generated by Django 4.1.7 on 2023-07-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0019_mensactiveweartop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensactiveweartop',
            name='place_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchprofile.searchresult'),
        ),
        migrations.CreateModel(
            name='MensActivewearPant',
            fields=[
                ('genericmenspant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.genericmenspant')),
                ('place_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchprofile.searchresult')),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.genericmenspant',),
        ),
    ]
