# Generated by Django 4.1.7 on 2023-07-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0021_menshoodiessweaters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensHoodiesSweaters',
            new_name='MensHoodiesSweatshirts',
        ),
    ]
