# Generated by Django 4.1.7 on 2023-10-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0025_genericwomenstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericwomenstop',
            name='collar',
        ),
        migrations.AddField(
            model_name='genericwomenstop',
            name='top_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
