# Generated by Django 4.1.7 on 2023-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0026_remove_genericwomenstop_collar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericwomenstop',
            name='neck_line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
