# Generated by Django 4.1.7 on 2023-10-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0027_genericwomenstop_neck_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomensDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage', models.CharField(blank=True, max_length=30, null=True)),
                ('condition', models.CharField(blank=True, max_length=30, null=True)),
                ('size_type', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('pattern', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('fit', models.CharField(blank=True, max_length=30, null=True)),
                ('fabric', models.CharField(blank=True, max_length=30, null=True)),
                ('item_model', models.CharField(blank=True, max_length=100, null=True)),
                ('sleeve_length', models.CharField(blank=True, max_length=30, null=True)),
                ('dress_type', models.CharField(blank=True, max_length=30, null=True)),
                ('neck_line', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchprofile.searchresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
