# Generated by Django 4.1.7 on 2023-10-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0028_womensdress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womensdress',
            old_name='dress_type',
            new_name='dress_style',
        ),
    ]
