# Generated by Django 4.1.7 on 2023-10-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0029_rename_dress_type_womensdress_dress_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='womensdress',
            name='dress_length',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
