# Generated by Django 4.1.7 on 2023-11-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0030_womensdress_dress_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomensJeans',
            fields=[
                ('genericmenspant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchprofile.genericmenspant')),
            ],
            options={
                'abstract': False,
            },
            bases=('searchprofile.genericmenspant',),
        ),
    ]
