# Generated by Django 4.1.7 on 2023-11-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofile', '0031_womensjeans'),
    ]

    operations = [
        migrations.AddField(
            model_name='womensjeans',
            name='jean_style',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
